---
deployment:
  tasks:
    - export DEPLOYPATH=/home/simpxlow/bingomaker.alloccasionsprintables.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/public/free-square
    - /bin/cp -R public/free-square/* $DEPLOYPATH/public/free-square/
    - /bin/mkdir -p $DEPLOYPATH/public/thank-you
    - /bin/cp -R public/thank-you/* $DEPLOYPATH/public/thank-you/
