---
deployment:
  tasks:
    - export DEPLOYPATH=/home/simpxlow/bingomaker.alloccasionsprintables.com/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/assets/free-square
    - /bin/cp assets/free-square/*.svg $DEPLOYPATH/assets/free-square/
